import express from "express";
import path from "path";
import { createServer as createViteServer } from "vite";
import { GoogleGenAI } from "@google/genai";
import dotenv from "dotenv";

dotenv.config();

const app = express();
const PORT = 3000;

app.use(express.json({ limit: "10mb" }));

// Lazy initialization of GoogleGenAI
function getGenAI() {
  const apiKey = process.env.GEMINI_API_KEY;
  if (!apiKey) {
    throw new Error("GEMINI_API_KEY environment variable is missing.");
  }
  return new GoogleGenAI({
    apiKey,
    httpOptions: {
      headers: {
        "User-Agent": "aistudio-build",
      },
    },
  });
}

// AI Chatbot Route
app.post("/api/chat", async (req, res) => {
  try {
    const { messages, portalContext } = req.body;

    if (!messages || !Array.isArray(messages) || messages.length === 0) {
      return res.status(400).json({ error: "Invalid messages payload." });
    }

    const ai = getGenAI();

    // Build context string from live portal database
    let contextText = "No portal database snapshot provided.";
    if (portalContext) {
      const { cases, landDisputes, udCases, ios, dailyReports, userRole, userPS } = portalContext;

      contextText = `
SYSTEM DATABASE SNAPSHOT (CURRENT LIVE PORTAL DATA):
Active User Role: ${userRole || "SDPO"}
Active Police Station Context: ${userPS || "All Police Stations (SDPO Tarapur)"}

--- FIR CASES (${cases?.length || 0} TOTAL) ---
${JSON.stringify(cases || [], null, 2)}

--- LAND DISPUTES (${landDisputes?.length || 0} TOTAL) ---
${JSON.stringify(landDisputes || [], null, 2)}

--- UD (UNNATURAL DEATH) CASES (${udCases?.length || 0} TOTAL) ---
${JSON.stringify(udCases || [], null, 2)}

--- INVESTIGATING OFFICERS / IOs (${ios?.length || 0} TOTAL) ---
${JSON.stringify(ios || [], null, 2)}

--- DAILY CRIME REPORTS (${dailyReports?.length || 0} TOTAL) ---
${JSON.stringify(dailyReports || [], null, 2)}
`;
    }

    const systemInstruction = `
You are "Tarapur AI Assistant", an intelligent police subdivision AI assistant & data analyst for SDPO Tarapur (Sub-Divisional Police Officer) in Bihar, India.
Your task is to answer questions, query police database records, list specific case details, provide supervision summaries, track 60/90-day investigation deadlines, monitor IO workloads, land disputes, UD cases, and daily crime reports.

CRITICAL INSTRUCTIONS & BEHAVIOR:
1. DATA ACCURACY: Always query and analyze the provided LIVE PORTAL DATA SNAPSHOT below. Do not invent fake FIR numbers, IO names, or case statuses.
2. FLEXIBLE QUERY HANDLING:
   - Murder cases: Filter FIR cases where sections or crime category includes murder, 302 IPC, 103 BNS, or murder/homicide keywords.
   - Pending Supervision cases: Filter cases where designation is 'SR' or status is 'Pending', or sdpoSupervisionNote exists/missing, or supervision is requested/required.
   - Specific IO cases: Filter cases where ioName matches or contains the IO name asked by user (e.g. "Inspector Kumar", "Ram", "Singh").
   - Deadline compliance: Calculate days elapsed since FIR date or date of occurrence and compare against target deadlines (60 days for normal, 90 days for major crimes).
   - Land Disputes & UD Cases: Extract and report exact details from the land disputes and UD case arrays.
3. OUTPUT FORMATTING:
   - Use clean Markdown formatting (bold headers, bullet points, structured tables when listing multiple cases).
   - Highlight key metadata for cases: FIR No., Police Station (PS), Sections/IPC/BNS, Case Status, IO Name, Date of Occurrence, Target Deadline, CCTNS status, Supervision Directives.
   - Keep answers professional, concise, authoritative, and helpful to police officers, CIs, and SDPO.
   - If no matching cases are found in the database, clearly inform the user and state what was checked.

${contextText}
`;

    // Format conversation history
    const history = messages.slice(0, -1);
    const lastUserMessage = messages[messages.length - 1].content;

    let formattedPrompt = "";
    if (history.length > 0) {
      formattedPrompt += "Previous conversation history:\n";
      history.forEach((m: { role: string; content: string }) => {
        formattedPrompt += `${m.role.toUpperCase()}: ${m.content}\n`;
      });
      formattedPrompt += "\nLatest User Question:\n";
    }
    formattedPrompt += lastUserMessage;

    const response = await ai.models.generateContent({
      model: "gemini-3.6-flash",
      contents: formattedPrompt,
      config: {
        systemInstruction,
        temperature: 0.2,
      },
    });

    const replyText = response.text || "No response generated by Gemini AI.";
    return res.json({ text: replyText });
  } catch (error: any) {
    console.error("Error in /api/chat:", error);
    return res.status(500).json({
      error: error.message || "Failed to generate AI response.",
    });
  }
});

async function startServer() {
  if (process.env.NODE_ENV !== "production") {
    const vite = await createViteServer({
      server: { middlewareMode: true },
      appType: "spa",
    });
    app.use(vite.middlewares);
  } else {
    const distPath = path.join(process.cwd(), "dist");
    app.use(express.static(distPath));
    app.get("*", (req, res) => {
      res.sendFile(path.join(distPath, "index.html"));
    });
  }

  app.listen(PORT, "0.0.0.0", () => {
    console.log(`Server running on http://0.0.0.0:${PORT}`);
  });
}

startServer();
